//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudarikov3ISP1113.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseaseHistory
    {
        public int IdDiseaseHistiry { get; set; }
        public int IdCard { get; set; }
        public int IdTicket { get; set; }
        public int IdDiagnos { get; set; }
    
        public virtual Diagnos Diagnos { get; set; }
        public virtual MedicalCard MedicalCard { get; set; }
    }
}
