//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudarikov3ISP1113.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int IdReceipt { get; set; }
        public int ServiceCost { get; set; }
        public int IdTicket { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
